---
title: "Time Series:Global Change"
author: "Sung Inkyung"
date: '2021 6 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(timetk)
library(sweep)
library(forecast)
```
###Source[Timetk] (https://towardsdatascience.com/timetk-the-r-library-for-time-series-analysis-9822f7720318)

```{r}
mobile <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/mobile.csv')

landline <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/landline.csv')
```


```{r}
summarize_subscription <- function(tbl) {
  tbl %>%
    summarize(n_obs = n(),
              total_subscriptions = sum(subscriptions,
                                        na.rm = TRUE)) %>%
    arrange(desc(total_subscriptions))
 
}


mobile <- mobile %>%
  rename(subscriptions = mobile_subs) %>%
  mutate(type = "Mobile")

landline <- landline %>%
  rename(subscriptions = landline_subs) %>%
  mutate(type = "Landline")

phones <- bind_rows(mobile, landline) %>%
  rename(country = entity)

phones
```

```{r}
year_phones <- phones %>% 
  mutate(year = as.Date(paste0(year, "-01-01"))) %>% 
  group_by(year, type) %>% 
  summarize_subscription() %>% 
  ungroup() %>% 
  select(-n_obs) %>% 
  rename(date = year)
```


```{r}
year_phones %>% 
  filter(type == "Mobile") %>% 
  plot_time_series(date, total_subscriptions)

year_phones %>% 
  filter(type == "Mobile") %>% 
  plot_time_series(date, total_subscriptions,
                   .interactive = T,
                   .plotly_slider = T)
```

```{r}
plot_phones_ts <- year_phones %>% 
  group_by(type) %>% 
  plot_time_series(date, total_subscriptions, 
                   .facet_scales = "free")

plot_phones_anomaly <- year_phones %>% 
  group_by(type) %>% 
  plot_anomaly_diagnostics(date, total_subscriptions)
```
### Source[data screencast by david robinson] (https://github.com/dgrtwo/data-screencasts/blob/master/2021_06_08_great_lakes_fish.Rmd)
```{r}
df_landline <- year_phones %>% 
  filter(type == "Landline")

time_series <- df_landline %>% 
  tk_ts(start = min(date(.$date)), frequency = 1)

ets_mod <- time_series %>% 
  ets()

ets_mod %>% 
  sw_tidy()

ets_mod %>% 
  sw_augment() %>% 
  ggplot(aes(index, .actual)) +
  geom_line() +
  geom_line(aes(y = .fitted), 
            color = "steelblue") +
  labs(x = "Time",
       y = "Total subscription of landline")

fcast <- ets_mod %>% 
  forecast(h = 10)


fcast_holt <- holt(time_series)
fcast_ses <- ses(time_series)

autoplot(time_series) +
  autolayer(fcast_holt, series = "Holt", PI = F) +
  autolayer(fcast_ses, series = "SES", PI = F)

```


```{r}
time_series <- year_phones %>% 
  filter(type == "Mobile") %>% 
  select(-type) %>% 
  tk_ts(start = min(date(.$date)), frequency = 1)

forecasts <- year_phones %>% 
  group_by(type, date) %>% 
  summarise(total_subscriptions = sum(total_subscriptions),
            .groups = "drop") %>% 
  nest(data = c(-type)) %>% 
  mutate(time_series = map(data, ~tk_ts(., start = min(date(.$date)),
                                         frequency = 1))) %>% 
  mutate(holt = map(time_series, holt, h = 20),
         ses = map(time_series, ses, h = 20))

forecasts %>% 
  mutate(forecast_sweep = map(holt, sw_sweep)) %>% 
  unnest(forecast_sweep) %>% 
  ggplot(aes(index, total_subscriptions)) +
  geom_line() +
  geom_ribbon(aes(ymin = lo.80,
                  ymax = hi.80),
              alpha = .2) +
  facet_wrap(~type) +
  theme_light()

fcast_holt <- holt(time_series, h = 50)
fcast_holt_dumped <- holt(time_series, damped = T, h = 50)
fcast_ses <- ses(time_series, h = 50)

autoplot(time_series) +
  autolayer(fcast_holt, series = "Holt", PI = F) +
  autolayer(fcast_holt, series = "Holt (Dumped)",
            PI = F) +
  autolayer(fcast_ses, series = "SES", PI = F)
  
```


