---
title: "Time Series:Downwards"
author: "Sung Inkyung"
date: '2021 6 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[timetk package] (https://towardsdatascience.com/timetk-the-r-library-for-time-series-analysis-9822f7720318)
```{r}
library(tidyverse)
library(timetk)
library(sweep)
library(forecast)
library(lubridate)
library(scales)
```


```{r}
fishing <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-08/fishing.csv') %>% 
  filter(values >= 0)
```


```{r}

summarize_fishing <- function(tbl) {
  tbl %>%
    summarize(n_obs = n(),
              total_production = sum(values, na.rm = TRUE)) %>%
    arrange(desc(total_production))
}

year_species <- fishing %>%
  mutate(year = as.Date(paste0(year, "-01-01"))) %>% 
  group_by(year, species) %>% 
  summarize_fishing() %>% 
  ungroup() %>% 
  select(-n_obs) %>% 
  rename(date = year)


year_species %>% 
  filter(species == "Cisco") %>% 
 plot_time_series(date, total_production)

year_species %>% 
  filter(species == "Cisco") %>% 
  plot_time_series(date, total_production,
                   .interactive = T,
                   .plotly_slider = T)

```
```{r}
year_species %>% 
  add_count(species) %>% 
  distinct(species)

top_5 <- c("Alewife", "Cisco", "Rainbow Smelt", "Yellow Perch", "Chubs")

plot_species_ts <- year_species %>% 
  filter(species %in% top_5) %>% 
  group_by(species) %>% 
  plot_time_series(date, total_production, 
                   .facet_scales = "free")

plot_species_anom <- year_species %>% 
  filter(species %in% top_5) %>% 
  group_by(species) %>% 
  plot_anomaly_diagnostics(date, total_production)

```
