---
title: "day2 pictogram"
output: html_document
date: '2022-04-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggimage)
library(ggforce)
library(showtext)

font_add_google("Concert One") 
font_add_google("Coda") 

f1 = "Concert One"
f2 = "Coda"

showtext_opts(dpi = 320)
showtext_auto()
```

```{r}
##https://github.com/gkaramanis/tidytuesday/blob/master/2020/2020-week19/animal-crossing.R

villagers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv')

village_people <- villagers %>% 
  add_count(species, personality) %>% 
  group_by(personality) %>% 
  arrange(species) %>% 
  mutate(id = row_number()) %>% 
  ungroup() 

ggplot(village_people) +
  geom_mark_ellipse(aes(id, personality, filter = n > 4, fill = species), 
                    color = NA, alpha = 1, position = position_nudge(y = -0.2),
                    expand = unit(1.4, "mm")) +
  geom_image(aes(id, personality, image = url), asp =2, size = 0.05, by = "height" ) +
  scale_fill_manual(values = c(rep("#dbfd6a", 7))) + ##c4c163
  coord_fixed(ratio = 4, clip = "off") +
  labs(title = "Personalities of Animal Crossing Villagers",
       subtitle = "Peppy rabbit, lazy dog, cranky bear, snooty & peppy cat, jock frog, normal squirrel, cranky wolf",
       caption = "Source: #TidyTuesday2020 Week19 VillagerDB | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#32a852", color = NA),
        plot.title = element_text(family = f1, size = 32, face = "bold", hjust = 0.5, color = "#fff563"),
        plot.subtitle = element_text(family = f2, size = 14, hjust = 0.5, color = "#dbfd6a", margin = margin(b = 15)),
        plot.caption = element_text(family = f1, size = 10, hjust = 0.5, color = "#81f1f7"),
        axis.text.y = element_text(family = f2, size = 12, hjust = 1, color = "#fffffa"),
        plot.margin = margin(20, 20, 20, 20))

ggsave("day2_pictogram.png", dpi = 320, width = 35, height = 20, units = "cm")
```

