---
title: "day14 Space"
author: "Sung Inkyung"
date: '2022 1 20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(lubridate)
library(scales)
library(poissoned)
library(showtext)

font_add_google("Orbitron")
font_add_google("Teko")
font_add_google("Assistant")

showtext_opts(dpi = 320)
showtext_auto()

```


```{r}
meteorites <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")

df <- meteorites %>%
  mutate(name =  str_replace_all(name, '\\d', ''),
         name = str_replace_all(name, '\\(.*\\)', ''),
         name = str_replace_all(name, '\\s\\w$', ''),
         name = str_trim(name)) %>% 
  mutate(mass = round(mass / 1000, 0)) %>% # g to kg
  mutate(decade = floor(year / 10) * 10) %>% 
  na.omit() %>% 
  filter(year <= 2022)

range(df$year)
range(df$mass)

df_plot <- df %>% 
  group_by(decade, mass, fall) %>% 
  summarise(n = n_distinct(decade)) %>% 
  arrange(desc(n)) %>% 
  filter(mass > 10)

range(df_plot$decade)

df_grid <- df_plot %>% 
  rowwise() %>% 
  mutate(decade = as.factor(decade),
         t = log10(mass),
         pnts = list(poisson_disc(ncols = t, nrows = t, cell_size = 1 / t))) %>% 
  ungroup() %>% 
  unnest(pnts)
```


```{r}
plot <- 
  ggplot() +
  geom_tile(data = df_grid,
            aes(0.5, 0.5, width = 1.1, height = 1.1), fill = "#5e9dc6", stat = "unique", show.legend = F) +
  geom_point(data = df_grid,
             aes(x, y, size = mass),
             color = "#c0643f",
             alpha = 0.6)  +
  scale_size(range = c(0.5, 4)) +
  scale_color_identity() +
  facet_grid(fall ~ decade, switch = "both") +
  labs(x = "",
       y = "",
       title = "Meteorites Impacts by Fall Types (1390-2010)",
       subtitle = "Fall types are divided into **FALL(233 cases)** and **FOUND(650 cases)**",
       caption = "Source: NASA | Graphic: Sung Inkyung") +
  guides(size = guide_legend(title = "Mass(kg)",
                             nrow = 1, byrow = TRUE)) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.background = element_rect(fill = "#3e3e3e",
                                         color = NA),
        legend.title = element_text(color = "#c9c7c5",
                                   family = "Assistant",
                                   size = 10),
        legend.text = element_text(color = "#c9c7c5",
                                   family = "Assistant",
                                   size = 9),
        legend.key = element_blank(),
        plot.background = element_rect(fill = "#3e3e3e", color = NA),
        panel.background = element_rect(fill = "#3e3e3e", color = NA),
        strip.background = element_rect(fill = "#3e3e3e",
                                        color = NA),
        strip.text.y = element_text(color = "#dfae91",
                                  family = "Teko",
                                  size = 18,
                                  margin = margin(r = 10)),
        strip.text.x = element_text(color = "#c9c7c5",
                                  family = "Teko",
                                  size = 9),
        plot.title = element_text(color = "#c0c0c0",
                                  family = "Orbitron",
                                  size = 22,
                                  margin = margin(b = 7)),
        plot.subtitle = element_markdown(color = "#c0c0c0",
                                         family = "Assistant",
                                         size = 13,
                                         margin = margin(b = 15)),
        plot.caption = element_text(color = "#bcbcbc",
                                    family = "Teko",
                                    size = 10),
        axis.text = element_blank(),
        plot.margin = margin(15, 15, 10, 15))

ggsave("day14_Space.png", width = 30, height = 17, units = "cm")
  
```

