---
title: "day13 Correlation"
author: "Sung Inkyung"
date: '2021 6 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(widyr)
library(igraph)
library(ggraph)
library(patchwork)
```


  
```{r}
bible <- read.csv("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/bible_kjv_new.csv")

ephesians <- read.csv("C:/Users/inkyscope/Documents/projectR/inkyscroll/data/Ephesians_Books.csv")

eph_stopwords <- c("ye", "god", "thou", "thy", "hath", "thee", "hast", "shalt", "thine", "yea", "art", "till", "fro", "nay", "saith")


df_books <- bible %>% 
  inner_join(ephesians, by = c("book", "chapter", "verse")) %>% 
  select(book, text) %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% eph_stopwords) %>% 
  anti_join(stop_words, by = "word") %>% 
  count(book, word, sort = T) %>% 
  bind_tf_idf(word, book, n) %>% 
  #slice_max(n = 2000, order_by= tf_idf) %>% 
  mutate(tf_idf = round(tf_idf * n, 2))

set.seed(123)

plot_books <- df_books %>% 
  pairwise_cor(book, word, tf_idf, sort = T) %>% 
  filter(correlation >= 0.05) %>% 
  graph_from_data_frame() %>% 
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation),
                 show.legend = F) +
  geom_node_point(color = "#c3272b",
                  size = 3.5) +
  geom_node_text(aes(label = name),
                 hjust = .5,
                 repel = T) +
  theme_void() +
  theme(plot.background = element_rect(fill = "#f0f8ff", 
                                   colour = "#f0f8ff"))

# ggsave(here::here("day13", "day13_Correlation.png"))


```

```{r}
df_words <- bible %>% 
  inner_join(ephesians, by = c("book", "chapter", "verse")) %>% 
  select(book, text) %>% 
  unnest_tokens(word, text) %>% 
  filter(!word %in% eph_stopwords) %>% 
  anti_join(stop_words, by = "word") %>% 
  count(word, book) %>% 
  add_count(book, wt = n, name = "book_count") %>% 
  filter(book_count > 30) %>% 
  add_count(word, wt = n, name = "word_count") %>% 
  filter(word_count >= 10) 

  
plot_words <- df_words %>% 
  mutate(color = case_when(
    book == "Ephesians" ~ "#663068",
    book == "Acts" ~ "#0ff1ce",
    book == "John" ~ "#FF6700",
    book == "Matthew" ~ "#008080",
    book == "Galatians" ~ "#00ccff",
    book == "Romans" ~ "#f7347a",
   #book == "Colossians" ~ "#ff7256",
   #book == "Deuteronomy" ~ "#3d0623",
   #book == "Psalms" ~ "#e7baa0",
   #book == "Genesis" ~ "#7ac5cd",
   #book == "Revelation" ~ "#6d7973",
     T ~ "gray40"
    )) %>% 
  ggplot(aes(x = 0,
             y = word,
             xend = book,
             yend = 1,
             color = "color",
             alpha = (color != "gray70")
            )) +
  geom_curve(aes(color = color),
             curvature = -.5,
             arrow = arrow(length = unit(.01, "npc")),
             show.legend = F) +
  scale_x_discrete() +
  scale_y_discrete() +
  scale_color_identity() +
  scale_alpha_manual(values = c(.7, .3), guide = F) +
  scale_size_manual(values = c(.1, .5), guide = F) +
  labs(x= " ",
       y= " ") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#f0f8ff", 
                                   colour = "#f0f8ff"),
        panel.grid = element_blank(),
        axis.text.x = element_text(size = 10,
                                   angle = 40,
                                   hjust = 1,
                                   margin = margin(t = -3, r = 0, b = 0, l = 0)))
```


```{r}
plot <- plot_books + plot_words +
  plot_annotation(title = "Coocurring Books and Words Relating To Book of Ephesians",
                  subtitle = "List of words along with books are cross-referenced during preaching of Ephesians<br>delivered by Pastor Cho JungMin from November 22, 2020 to March 7th, 2021 at Basic Church.<br>A sermon on Ephesians is about <**What kind of church we should be**>",
                  caption = "Source: #30DayChartChallenge | Graphic: Sung Inkyung") &
  theme(plot.title = element_text(size = 24,
                                  face = "bold",
                                  margin = margin(b = 9)),
        plot.subtitle = element_markdown(size = 16, 
                                         lineheight = .7,
                                         margin = margin(b = 15)),
        plot.caption = element_text(size = 9,
                                    margin = margin(t = 20, b = 10)))

ggsave(here::here("day13", "day13_Correlation.png"), dpi = 300, width = 35, height = 22,  units = "cm")

```

