---
title: "10. Abstact"
author: "Sung Inkyung"
date: '2021 5 29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(imager)
library(tidyverse)
library(ggvoronoi)
library(kableExtra)
library(here)
library(showtext)

font_add_google("Rajdhani")

showtext_opts(dpi = 320)
showtext_auto(enable = T)
```

### Source[30DCC by CS Hoggard] (https://github.com/CSHoggard/30DayChartChallenge)
```{r}
img <- load.image("data/leaf.jpg")

df_img <- as.data.frame(img)
```


```{r}
 df_img %>% 
  arrange(x, y, cc) %>% 
  filter(row_number() < 10) %>% 
  kable("html") %>% 
  kable_styling(full_width = F)

df_moran <- df_img %>% 
  mutate(channel = case_when(
    cc == 1 ~ "Red",
    cc == 2 ~ "Green",
    cc == 3 ~ "Blue"
  ))

df_wide <- df_moran %>% 
  select(x, y, channel, value) %>% 
  pivot_wider(names_from = "channel", values_from = "value") %>% 
  mutate(color = rgb(Red, Green, Blue))

sample_size <- 100000
img_sample <- df_wide[sample(nrow(df_wide), sample_size), ]
img_sample$size <- runif(sample_size)


df_voronoi <- img_sample %>% 
  ggplot() +
  geom_jitter(aes(x, y, color = color, size = size), alpha = 0.4) +
  scale_color_identity() +
  scale_y_reverse() +
  guides(size = F) +
  labs(caption = "Graphic: Sung Inkyung") +
  theme_void() +
  theme(plot.background = element_rect(fill = "gray95",
                                       color = NA),
        plot.caption = element_text(size = 9,
                                    family = "Rajdhani",
                                   margin = margin(t = 15)),
        plot.margin = margin(20, 20, 20, 20))

ggsave("day10_abstract.png", dpi = 300, width = 24, height = 18, units = "cm")
```

