---
title: "day23 Tiles"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggsci)
library(scales)
library(showtext)

font_add_google("Anton")
font_add_google("Fira Sans")
font_add_google("Saira")

showtext_opts(dpi = 320)
showtext_auto()

f1 = "Anton"
f2 = "Fira Sans"
f3 = "Saira"
```

```{r}
df <- read_csv("~/Documents/projectR/30DayChartChallenge/data/owid-covid-data.csv")

df_boosters <- df %>% 
  select(continent, date, total_boosters) %>% 
  filter(continent != "NA",
         total_boosters != "NA") %>% 
  group_by(continent) %>% 
  mutate(max_n = max(total_boosters))

ggplot(df_boosters) +
  geom_segment(aes(x = date, xend = date, y = 0, yend = 1, color = log10(total_boosters)), size = 0.75) +
  geom_text(data = df_boosters %>% 
              filter(date == min(date)),
            aes(x = as.Date("2021-01-01"), y = 0, color = log10(max_n),
                label = continent), size = 14, family = f1, hjust = 0, vjust = 0) +
  scale_y_continuous(limits = c(0, 1.3)) + 
  scale_x_date() +
  scale_color_material(palette = "light-green") +
  guides(color = guide_colorbar(title.position = "top", title.hjust = 0.5, title = "Total boosters(log10)")) +
  facet_wrap(~reorder(continent, desc(max_n)), ncol = 1) +
  labs(x = "", y = "", 
       title = "THE WORLD COVID-19 BOOSTERS STATUS",
       caption = "Source: Our World in Data | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(1.3, "cm"),
        legend.text = element_text(family = f3, size = 11, color = "#012401"),
        strip.text = element_blank(),
        plot.background = element_rect(fill = "snow2", color = NA),
        panel.background = element_rect(fill = "snow2", color = NA),
        plot.title = element_text(family = f1, size = 38, hjust = 0.5, color = "#012401", margin = margin(b = 15)),
        plot.caption = element_text(family = f3, size = 10, hjust = 0.95, color = "snow4", margin = margin(t = 15)),
        panel.grid = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(family = f3, size = 12, color = "#012401"),
        plot.margin = margin(20, 20, 20, 20))

ggsave("day23_tiles.png", width = 30, height = 22, units = "cm")
```
