---
title: "day22 Animation"
author: "Sung Inkyung"
date: '2021 5 30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggsci)
library(gganimate)
```

```{r}
load("C:/Users/inkyscope/Documents/projectR/30DayChartChallenge/data/gapminder.rda")


df <- gapminder %>% 
  as_tibble() %>% 
  filter(!is.na(fertility),
         !is.na(life_expectancy),
         !is.na(population))

plot <- df %>% 
  ggplot(aes(fertility, life_expectancy, 
             fill = continent,
             size = population,
             group = country)) +
  geom_point(shape = 21, 
             alpha = 0.7) +
  scale_fill_d3(name = " ") +
  scale_size(range = c(4, 30), 
             guide = "none") +
  scale_x_continuous(breaks = seq(2, 8, 2)) +
  scale_y_continuous(breaks = seq(20, 80, 20)) +
  labs(x = "Fetility Rate (Births per woman)",
       y = "Life expectancy at birth",
       title = "Gapminder | Year {frame_time}",
       subtitle = "Life expectancies and fertility rates between 1960 and 2015 in the world",
       caption = "Source: DS Labs package | Graphic: Sung Inkyung") +
  view_follow(fixed_y = TRUE) +
  theme_minimal() +
  transition_time(year) +
  ease_aes("linear") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  theme(legend.position = "bottom",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 11),
        plot.caption = element_text(size = 7)) 


anim_save("day22_life_experience.gif")

```

