---
title: "day5 Slope"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggtext)
library(showtext)

font_add_google("Bebas Neue")
font_add_google("Fira Sans")

showtext_opts(dpi = 320)
showtext_auto()

f1 = "Bebas Neue"
f2 = "Fira Sans"
```

```{r}
expeditions <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/expeditions.csv')


df_plot <- expeditions %>% 
  mutate(decade = floor(year / 10) * 10) %>% 
  mutate(status = ifelse(str_detect(termination_reason, "Success"), "Success", "Failure")) %>% 
  group_by(decade) %>% 
  count(status) %>% 
  filter(decade >= 1950) %>% 
  arrange(status)

  range(df_plot$decade)

plot <- ggplot(df_plot, aes(decade, n, group = status)) +
  geom_line(data = df_plot %>% 
              filter(status == "Failure"), 
            color = "#BFAA57") +
  geom_point(data = df_plot %>% 
               filter(status == "Failure"), 
             color = "#BFAA57", size = 2) +
  geom_line(data = df_plot %>% 
              filter(status == "Success"),  
            size = 1.05, color = "#D81E5B") +
  geom_point(data = df_plot %>% 
               filter(status == "Success"), 
             size = 3.5, color = "#D81E5B") +
  geom_text(data = df_plot %>% 
              filter(decade %in% c(1950, 1980, 1990, 2000, 2010)),
            aes(label = n), family = f2, size = 3.4, hjust = 1.2, vjust = -0.4) +
  geom_vline(aes(xintercept = 1990), size = 0.7, color = "#D81E5B", linetype = "dotted") +
  scale_x_continuous(limits = c(1950, 2010),
                     breaks = seq(1950, 2010, 20)) +
  labs(x = "", y = "",
       title = "<span style = 'color:#D81E5B'>**Success**</span> and <span style = 'color:#BFAA57'>**Failure**</span> in the Himalayas 1950 - 2010",
       caption = "Source: The Himalayan Database | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "snow1", color = NA),
        plot.title = element_markdown(family = f1, size = 26, hjust = 0.5, margin = margin(b = 25)),
        plot.caption = element_text(family = f2, size = 9, margin = margin(t = 25)),
        axis.text.y = element_blank(),
        panel.grid = element_blank(),
        plot.margin = margin(20, 20, 20, 20))

ggsave("day5_slope.png", width = 20, height = 18, units = "cm")
```
