---
title: "Untitled"
author: "Sung Inkyung"
date: '2021 11 1 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[Tidytuesday by @jennschilling] (https://github.com/jennschilling/tidytuesday-2021/blob/c53722392efba4fede9b45ac1fddea95d69bca4d/2021-07-06/2021-07-06.R)
```{r}
library(tidyverse)
library(ggtext)
library(lubridate)
```


```{r}
stepcounts <- readr::read_csv("C:/Users/inkyscope/Documents/projectR/30DayChartChallenge/data/inkystepcounts.csv") %>% 
  rename(weekday = "day") %>% 
  mutate(year = year(date),
         month = month(date),
         day = day(date),
         month = month.name[month]) 



# Calendar
cal <- tibble(
  date = seq(ymd(20150701), ymd(20211031), by = 1)
) %>% 
  mutate(week = as.numeric(format(date, "%U")))
```


```{r}
df <- stepcounts %>% 
  left_join(cal) %>% 
  mutate(weekday = factor(weekday, c("Sunday", "Monday", "Tuesday",
                                     "Wednesday", "Thursday", "Friday",
                                     "Saturday")),
         month = factor(month, c("January", "February", "March", "April",
                                 "May", "June", "July", "August",
                                 "September", "October", "November", "December"))) 

```


```{r}
plot <- df %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = weekday, y = week,
             fill = steps,
             label = day)) +
  geom_tile(color = "#efe7db") +
  geom_text(size = 6,
            color = "gray30") +
  scale_x_discrete(labels = c("Sunday" = "Sun",
                              "Monday" = "Mon",
                              "Tuesday" = "Tue",
                              "Wednesday" = "Wed",
                              "Thursday" = "Thur",
                              "Friday" = "Fri",
                              "Saturday" = "Sat")) +
  scale_y_reverse() +
  scale_fill_gradient(low = "#e9e4ed",
                      high = "#8d749e") +
  facet_wrap(~ month, 
             nrow = 4,
             scales = "free_y") +
  guides(fill = "none") +
  labs(title = "<span style = 'color: #8d749e'> **2 0 2 0**</span>",
       subtitle = "Daily strolling steps counts",
       caption = "Source: Personal data record | Graphic: Sung Inkyung") +
  theme_minimal() +
  theme(legend.position = "none",
  panel.background = element_rect(fill = "#efe7db", 
                                  color = NA),
  plot.background = element_rect(fill = "#efe7db",  
                                 color = NA),
  plot.title = element_markdown(size = 60,
                                color = "#134e41",
                                hjust = 0.5,
                                face = "bold",
                                margin = margin(t = 10, b = 7)),
  plot.subtitle = element_text(size = 28,
                               hjust = 0.5,
                               margin = margin( b = 20)),
  plot.caption = element_text(size = 16,
                              color = "#859e74",
                              hjust = 0.5,
                              margin = margin(t =20)),
  strip.text = element_text(size = 24, 
                            color = "#a7825d",
                            face = "bold",
                            hjust = 0.5),
  strip.background = element_blank(),
  axis.title = element_blank(),
  axis.text.x = element_text(size = 12, 
                           color = "gray30"),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  plot.margin = margin(10, 20, 10, 20))

ggsave(here::here("day23", "day23_tile.png"), width = 40, height = 40, dpi = 300, units = "cm")
```
