---
title: "day16 circle_trees"
author: "Sung Inkyung"
date: '2021 10 31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggraph)
library(igraph)
library(lubridate)
library(paletteer)
library(patchwork)
library(here)
library(showtext)

font.add.google("Saira")
font_add_google("Saira Condensed")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
tweet_df <- read_csv("C:/Users/inkyscope/Documents/projectR/30DayChartChallenge/data/tweets_ga.csv") %>% 
  mutate(hour = hour(created_at),
         day = day(created_at))

tweet_circle0 <- data.frame(from = "day", to = 0:23)

#day27

tweet_circle1 <- tweet_df %>% 
  filter(day == 27) %>% 
  filter(is_retweet) %>% 
  summarize(from = hour, to = retweet_status_id)

tweet_circle2 <- tweet_df %>% 
  filter(day == 27) %>% 
  filter(is_retweet) %>% 
  summarize(from = retweet_status_id, to = status_id)

edges <- rbind(tweet_circle0, tweet_circle1, tweet_circle2)
mygraph <- graph_from_data_frame(edges)

circle_depth <- c("day", "hour", "tweet", "retweets")


plot_circle1 <- ggraph(mygraph, layout = "circlepack") +
  geom_node_circle(aes(fill = factor(depth)),
                   color = "#cbbeb5",
                   size = 0.15) +
  scale_fill_paletteer_d("rockthemes::nodoubt",
                         labels = circle_depth) +
  labs(fill = "",
       title = "October 27, 2021") +
  coord_fixed() +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
#day30

tweet_circle1 <- tweet_df %>% 
  filter(day == 30) %>% 
  filter(is_retweet) %>% 
  summarize(from = hour, to = retweet_status_id)

tweet_circle2 <- tweet_df %>% 
  filter(day == 30) %>% 
  filter(is_retweet) %>% 
  summarize(from = retweet_status_id, to = status_id)

edges <- rbind(tweet_circle0, tweet_circle1, tweet_circle2)
mygraph <- graph_from_data_frame(edges)

circle_depth <- c("day", "hour", "tweet", "retweets")


plot_circle2 <- ggraph(mygraph, layout = "circlepack") +
  geom_node_circle(aes(fill = factor(depth)),
                   color = "#cbbeb5",
                   size = 0.15) +
  scale_fill_paletteer_d("rockthemes::nodoubt",
                         labels = circle_depth) +
  labs(fill = "",
       title = "October 30, 2021") +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))

```


```{r}
plot_circle1 + plot_circle2 +
  plot_annotation(title = "Retweets tagged with #generative art",
                  caption = "Source: Twitter | Graphic: Sung Inkyung | Credit: @gkaramanis",
                  theme = theme(
                    legend.text = element_text(family = "Saira Condensed",
                                               size = 9),
                    plot.title = element_text(size = 20,
                                              family = "Saira",
                                              hjust = 0.5,
                                              margin = margin(b = 15)),
                    plot.caption = element_text(size = 9,
                                                family = "Saira Condensed",
                                                hjust = 0.5,
                                                margin = margin(t = 20)),
                    plot.margin = margin(20, 10, 10, 10))) 
                  
ggsave("day16_circle_trees.png", width = 20, height = 16, units = "cm", dpi = 300)
```

