---
title: "day15 multivariate"
output: html_document
date: '2022-04-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#remotes::install_github("ricardo-bion/ggradar")
library(ggradar)
library(scales)
library(showtext)

font_add_google("Bebas Neue")
font_add_google("Saira")

showtext_opts(dpi = 320)
showtext_auto()

f1 = "Bebas Neue"
f2 = "Saira"
```

```{r}
## personal loan, Securities Account, CD Account, Online, Credit Card: 0:N, 1:Y
## Education: 1:Undergrad, 2:Graduate, 3: Advance/Professional
personal_loan <- read_csv("~/Documents/projectR/30DayChartChallenge/data/personaloan.csv") %>% 
  janitor::clean_names() %>% 
  select(-c(id, zip_code))

df_ploan <- personal_loan %>%  
  mutate_at(vars(-c(age, education, personal_loan)), scale) %>% 
  mutate(group = case_when(age >= 20 & age < 30 ~ "20 - 29",
                           age >= 30 & age < 40 ~ "30 - 39",
                           age >= 40 & age < 50 ~ "40 - 49",
                           age >= 50 & age < 60 ~ "50 - 59",
                           age >= 60 & age < 70 ~ "60 - 69 ",
                           TRUE ~ ">70")) %>% 
  relocate(group, personal_loan) %>% 
  group_by(group, education, loan = personal_loan) %>% 
  summarise(across(experience:credit_card, ~mean(.x, na.rm = TRUE))) %>% 
  ungroup()
  
plot <- df_ploan %>% 
  filter(loan == 1,
         education == 1) %>%
  select(-c(education, loan)) %>% 
  ggradar(grid.min = -3, grid.mid = 0, grid.max = 3,
          values.radar = c("-3", "0", "3"),
          grid.label.size = 3,
          axis.label.size = 3,
          axis.label.offset = 1.2,
          gridline.mid.colour = "gray60",
          group.line.width = 1, 
          group.point.size = 1.3,
          group.colours = "#144973"
  ) +
  facet_wrap(vars(group), ncol = 5) +
  labs(title = "Personal Loan Factors by Age Group",
       subtitle = "Education level: Undergraduate", 
       caption = "Source: Kaggle | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "none",
        strip.background = element_rect(fill = "firebrick4", color = NA),
        strip.text = element_text(family = f2, size = 13, face = "bold", hjust = 0.5, color = "white", margin = margin(5, 5, 5, 5)),
        panel.spacing = unit(1.3, "lines"),
        plot.background = element_rect(fill = "floralwhite", color = NA),
        plot.title = element_text(family = f1, size = 28, hjust = 0.5, margin = margin(b = 9)),
        plot.subtitle = element_text(family = f2, size = 16, hjust = 0.5, margin = margin(b = 35)),
        plot.caption = element_text(family = f2, size = 9, margin = margin(t = 20)),
        plot.margin = margin(20, 20, 10, 20))

ggsave("day15_multivariate1.png", width = 48, height = 20, units = "cm")
```

